import descriptions from './api_project_descriptions';
import projectImages from '../assets/images/project_images/project_images';
import tech from './api_technologies';

const projects = [
  // {
  //   id: 0,
  //   title: 'Hunting Buddy',
  //   description: [],
  //   projectLink: '',
  //   codeLink: '',
  //   imgArr: projectImages.jobBoard,
  //   tags: ['React', 'MERN', 'Full-Stack', 'Responsive Design', 'All'],
  //   skills: [],
  // },
  // {
  //   id: 1,
  //   title: 'PlaceBook',
  //   description: [],
  //   projectLink: '',
  //   codeLink: '',
  //   imgArr: projectImages.jobBoard,
  //   tags: [],
  //   skills: [],
  // },
  {
    id: 2,
    title: 'Pawnee Pets',
    description: descriptions.jobBoard,
    projectLink: 'http://pawnee-pets.katieloesch.co.uk',
    codeLink: 'https://github.com/katieloesch/project4-react-frontend',
    imgArr: projectImages.jobBoard,
    tags: ['React', 'Rails', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.react,
      tech.ruby,
      tech.rails,
      tech.css,
      tech.javascript,
      tech.heroku,
      tech.jwt,
      tech.postman,
    ],
  },
  {
    id: 3,
    title: 'Film & TV Stuff',
    description: descriptions.flicks4brains,
    projectLink: 'http://film-tv-stuff.katieloesch.co.uk',
    codeLink:
      'http://github.com/katieloesch/project-2-react-film-app-revisited',
    imgArr: projectImages.flicks4brains,
    tags: ['React', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.javascript,
      tech.react,
      tech.sass,
      tech.firebase,
      tech.firestore,
    ],
  },
  {
    id: 4,
    title: 'MERN Guestbook',
    description: descriptions.guestbook,
    projectLink: 'https://mern-guestbook.katieloesch.co.uk/',
    codeLink: 'https://github.com/katieloesch/p3-mern-guestbook-frontend',
    imgArr: projectImages.guestbook,
    tags: ['React', 'MERN', 'Full-Stack', 'Responsive Design', 'All'],
    skills: [
      tech.javascript,
      tech.react,
      tech.nodejs,
      tech.express,
      tech.mongodb,
      tech.mongoose,
      tech.tailwind,
      tech.postman,
      tech.passport,
      tech.jwt,
      tech.heroku,
    ],
  },
  {
    id: 5,
    title: 'Todo App',
    description: descriptions.pomodoro,
    projectLink: 'http://todo-app.katieloesch.co.uk/',
    codeLink: 'https://github.com/katieloesch/react-todo-app',
    imgArr: projectImages.pomodoro,
    tags: ['React', 'Responsive Design', 'All'],
    skills: [tech.javascript, tech.react, tech.redux, tech.css],
  },
  {
    id: 6,
    title: 'Tic Tac Toe',
    description: descriptions.browserArcade,
    projectLink: 'http://tictactoe.katieloesch.co.uk/',
    codeLink: 'http://github.com/katieloesch/project-1-tictactoe',
    imgArr: projectImages.arcade,
    tags: ['React', 'Responsive Design', 'All'],
    skills: [tech.javascript, tech.html, tech.css],
  },
];

export { projects };
